spring:
  application:
    name: product-management-api

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /docs